server:
  port: 8080
spring:
  datasource:
    driver-class-name: org.h2.Driver
    password: ''
    platform: h2
    url: jdbc:h2:mem:ProductServiceApp;DB_CLOSE_DELAY=-1;
    username: sa
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: false
        show_sql: false

management:
  endpoints:
    web:
      exposure:
        include: health
        exclude: